job1:
  only:
    - full
  tags:
    - bcm
  script:
    - mkdir build
    - python3 -m pip install --user -r requirements.txt
    - NUM_TIMES=20 METRIC=dendrogram_purity python3 reproduce_experiment.py
    - python3 -m pip install --user matplotlib
    - python3 plotter.py --format svg --filename z_in_1
    - python3 plotter.py --format svg --filename z_in_2
    - python3 plotter.py --format svg --filename z_o
  artifacts:
    paths:
      - build/z_in_1.svg
      - build/z_in_2.svg
      - build/z_o.svg

