os: linux
dist: xenial
language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - pip install pylint==2.5.2
script:
  - pylint plotter.py
  - python experiment_two_level.py --alg all
